


// ! MATERI ALERT DI REACT NATIVE


//!. 1. APA ITU ALERT
/*
        SEBUAH OBJECT ATAU FUNGSI YANG DIGUNAKAN UNTUK MENAMPILKAN PESAN PERINGATAN
*/

//TODO:BEDANYA DENGAN MODAL KLO MODAL DIGUNAKAN SEBAGAI COMPONENT SEDANGKANT ALERT DIGUNAKAN SEBAGAI FUNGSI 


//! 2.CARA MENGGUNAKAN FUNGSI ALERT
/*

    TODO: IMPORT TERLEBIH DAHULU OBJECTNNYA Alert


    * ADA BANYAK METHOD YG BISA DIGUNAKAN DI OBJECT Alert
    
    * 1. alert(title,description,(button_alert([...obj]))[{}]) = fungsi untuk membuat alert informasi


*/