

//! MATERI CORE COMPONENT SCROLL VIEW REACTT NATIVE


//! 1. APA ITU SCROLL VIEW
/*
    SCROLL VIEW ADALAH SALAH SATU CORE COMPONENT YG DIGUNAKAN UNTUK MEMBUAT UNTUK MEMBUAT CONTAINER UNTUK COMPONENT DAN SUPAYA BISA DI SCROLL ATAU SCROLABLE
*/

// TODO: JADI HAMPIR SAMA DENGAN VIEW BEDANYA VIEW TIDAK BISA DI SCROLL SEDANGKAN SCROLL VIEW BISA DI SCROLL


//! 2. CARA MENGGUNAKAN <ScrollView/>
/*

    * import componentnya

    * <ScrollView style ={{}} {...props} />

*/