

//! MATERI NAVIGATION DI REACT NATIVE

//! 1. APA ITU NAVIGATION
/*
    NAVIGATION ADALAH SEBUAH CARA UNTUK MENGHUBUNGKAN ATAU MENGARAHKAN USER KE HALAMAN LAIN
*/


//! 2. CARA MENGGUNAKAN NAVIGATION
/*

    TODO: EXPO
    * DI EXPO SUDAH ADA NAVIGATION BAWAAN DAN ROUTERNYA ITU BERBASIS FOLDER

    TODO: REACT CLI
    * DI REACT CLI KITA BISA MENGGUNAKAN PKG TAMBAHAN YG BERNAMA react-native-navigation

*/